[project]
name = "bikecounter"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "inference>=1.3.8",
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.10",
    "jupyterlab-vim>=4.1.4",
    "roboflow>=1.4.0",
    "supervision>=0.30.0",
    "tdqm>=0.0.1",
    "tqdm>=4.70.0",
    "ultralytics>=8.4.119",
]
